language: go

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2

script:
  - dep init
  - golangci-lint run --enable-all --exclude ^G104
  - make test
