language: go

go:
  - 1.13

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.23.6

script:
  - go mod vendor
  - go mod download
  - make lint
  - make test
