language: go

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.23.6

script:
  - GO111MODULE=on go mod vendor
  - GO111MODULE=on go mod download
  - golangci-lint run --enable-all --disable=gochecknoinits,gochecknoglobals,scopelint,gomnd
  - make test
